project_id = "bmjodfentjzgocqdpbje"

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-mcq]
verify_jwt = true

[functions.generate-concepts]
verify_jwt = true

[functions.process-pdf]
verify_jwt = true
